### ISSUE TITLE
Groups, scopes and NOT weirdness

### ISSUE THREAD

**Issue by North101** [isoos/query#5]
`(field:abc)` doesn't work.
```
end of input expected at 1:11
```

however `NOT field:abc` doesn't work and `NOT (field:abc)` does work
```
end of input expected at 1:10
```

Thanks for the library. I've been able to build a very powerful text -> sql query builder with it!

**Comment by isoos** [comment]
Hm, interesting, I don't really see why this wouldn't work for your first example:
https://github.com/isoos/query/blob/master/lib/src/grammar.dart#L74-L78

**Comment by North101** [comment]
```
  query:
    dependency: "direct main"
    description:
      name: query
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.4.0"
  petitparser:
    dependency: transitive
    description:
      name: petitparser
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.4.0"
```
I'm going to try downgrading petitparser and see if thats the cause.
